name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./train-of-thought

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Build
      working-directory: ./train-of-thought
      run: |
        sudo chmod +x ./build.sh
        npm run build
